# Generated by Django 4.1.5 on 2023-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
