# Generated by Django 4.2.2 on 2023-06-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_myexamcenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myexamcenter',
            options={'ordering': ['id']},
        ),
    ]
